import type { Metadata } from "next";
import { ThemeProvider } from "@/contexts/ThemeProvider";
import { Inter } from "next/font/google";
import "./globals.css";
import AOSInit from "@/components/aos/AOSInit";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Portfólio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br" className={inter.className}>
      <body>
        <ThemeProvider>
          <AOSInit />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
